[package]
name = "libradicl"
version = "0.1.0"
authors = ["Avi Srivastava <avi.srivastava@nyu.edu>", "Hirak Sarkar <hirak_sarkar@hms.harvard.edu>", "Rob Patro <rob@cs.umd.edu>"]
edition = "2018"

[dependencies]
scroll = "0.10.1"
num = "0.3.0"
fasthash = "0.4.0"
ahash = "0.4.4"
slog = "2.5.2"
bstr = "0.2.15"
slog-term = "2.6.0"
slog-async = "2.5.0"
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"
csv = "1.1.3"
dashmap = "^4.0.2"
indicatif = "0.15.0"
itertools = "0.10.0"
crossbeam-channel = "0.4.3"
crossbeam-queue = "0.2.3"
petgraph = "0.5.1"
executors = "0.7"
bio-types = "0.6.0"
quickersort = "3.0.1"
needletail = "0.4"
num-format = "0.4.0"
statrs = "0.13.0"
rand = "0.7.3"
flate2 = "1.0.16"
smallvec = "1.4.1"
serde_json = "1.0.57"
sprs = "0.8.1"
rust-htslib = { version = "0.36.0", default-features = false, features = ["bzip2", "lzma"] }
sce = { git = "https://github.com/parazodiac/SingleCellExperiment" }
